### ISSUE TITLE
How do you run this in Android Studio 

### ISSUE THREAD

**Issue by SimonBurfield** [dangngocduc/instagram_flutter#3]
I am learning Flutter and found this, when I execute it

Launching lib\main.dart on Android SDK built for x86 in debug mode...
Running Gradle task 'assembleDebug'...
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.18.1/lib/src/picture_provider.dart:50:59: Error: No named parameter with the name 'nullOk'.
        context != null ? Localizations.localeOf(context, nullOk: true) : null,
                                                          ^^^^^^
/C:/flutter/packages/flutter/lib/src/widgets/localizations.dart:413:17: Context: Found this candidate, but the arguments don't match.
  static Locale localeOf(BuildContext context) {
                ^^^^^^^^

**Comment by dangngocduc** [comment]
@SimonBurfield hi, this project is working fine with flutter 1.22.6 :D please check your version flutter.

**Comment by dangngocduc** [comment]
@SimonBurfield I have upgraded to null-safety, you can use with lastest version of Flutter.
